dist: 'trusty'
language: node_js
node_js:
  - '0.12.17'
services:
  - postgresql
addons:
  postgresql: '9.6'
before_install:
  - sudo apt-get install -y lsof
before_script:
  - createdb lisk_test
  - psql -d lisk_test -c "alter user "$USER" with password 'password';"
  - wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz
  - tar -zxvf lisk-node-Linux-x86_64.tar.gz
  - cd test/lisk-js/; npm install; cd ../..
  - cp test/config.json test/genesisBlock.json .
  - node app.js --coverage=true &> /dev/null &
env:
  global:
    - HOST=http://0.0.0.0:4000
  matrix:
    - TESTNAME=test/api/accounts.js COVERAGE_REPORT=true
    - TESTNAME=test/unit/helpers COVERAGE_REPORT=false
    - TESTNAME=test/unit/logic COVERAGE_REPORT=false
script: 'npm run coverageSingle'
after_success:
    - 'if [ ${COVERAGE_REPORT} = "true" ]; then
         npm run coveralls:func;
      else
         echo "Success, writing no coverage report.";
      fi'