dist: 'trusty'
language: node_js
node_js:
  - '0.12.17'
services:
  - postgresql
addons:
  postgresql: '9.6'
before_install:
  - sudo apt-get install -y lsof
before_script:
  - createdb lisk_test
  - psql -d lisk_test -c "alter user "$USER" with password 'password';"
  - wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz
  - tar -zxvf lisk-node-Linux-x86_64.tar.gz
  - cd test/lisk-js/; npm install; cd ../..
  - cp test/config.json test/genesisBlock.json .
  - node app.js --coverage=true &> /dev/null &
env:
  - TESTNAME=test/api/accounts.js
  - TESTNAME=test/api/blocks.js
  - TESTNAME=test/api/dapps.js
  - TESTNAME=test/api/delegates.js
  - TESTNAME=test/api/loader.js
  - TESTNAME=test/api/multisignatures.js
  - TESTNAME=test/api/peer.blocks.js
  - TESTNAME=test/api/peer.dapp.js
  - TESTNAME=test/api/peer.js
  - TESTNAME=test/api/peer.transactions.collision.js
  - TESTNAME=test/api/peer.transactions.delegates.js
  - TESTNAME=test/api/peer.transactions.main.js
  - TESTNAME=test/api/peer.transactions.signatures.js
  - TESTNAME=test/api/peer.transactions.stress.js
  - TESTNAME=test/api/peer.transactions.votes.js
  - TESTNAME=test/api/peers.js
  - TESTNAME=test/api/signatures.js
  - TESTNAME=test/api/transactions.js
  - TESTNAME=test/unit/helpers/request-limiter.js
  - TESTNAME=test/unit/logic/blockReward.js
script: 'npm run coverageSingle'
after_success:
  - npm run coveralls