dist: 'trusty'
language: node_js
node_js:
  - '0.12.17'
services:
  - postgresql
addons:
  postgresql: '9.6'
before_install:
  - sudo apt-get install -y lsof
before_script:
  - createdb lisk_test
  - psql -d lisk_test -c "alter user "$USER" with password 'password';"
  - wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz
  - tar -zxvf lisk-node-Linux-x86_64.tar.gz
  - cd test/lisk-js/; npm install; cd ../..
  - cp test/config.json test/genesisBlock.json .
  - node app.js --coverage=true &> /dev/null &
  - ps -xa | grep node
env:
  - TESTNAME=test/api/accounts.js
  - TESTNAME=test/api/peer.js
  - TESTNAME=test/unit/helpers/request-limiter.js
script: 'npm run coverageSingle'
after_success:
  - npm run coveralls
  - curl http://0.0.0.0:4000/coverage/download
  - cat node_modules/coveralls/bin/coveralls.js
  - cat ./test/.coverage-func/lcov.info
  - cat ./test/.coverage-func/lcov.info | node_modules/coveralls/bin/coveralls.js
after_failure:
  - npm run coveralls
  - curl http://0.0.0.0:4000/coverage/download
  - cat node_modules/coveralls/bin/coveralls.js
  - cat ./test/.coverage-func/lcov.info
  - cat ./test/.coverage-func/lcov.info | node_modules/coveralls/bin/coveralls.js


